### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by eezhal92** [eezhal92/resepku-node#1]
When performing a request `GET /recipes/1`, the returned response was "Cannot read property 'split' of undefined". This error occured because `fields` query string is not present in the request.

The request was valid because `fields` query string is not mandatory. It's because in this line https://github.com/eezhal92/resepku-node/blob/master/app.js#L45, the argument passed into `parseField` function was `undefined`.

The implementation to fix this is quite simple. To celebrate #hacktoberfest, I encourage You to make a Pull Request to fix this error.

Happy Coding!

**Comment by erickzhao** [comment]
Interested in solving this!

**Comment by eezhal92** [comment]
Hi @erickzhao, somebody opened this PR #5 and got merged. So, i'm going to close this issue. Thanks 👍
