### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by eezhal92** [eezhal92/resepku-node#14]
I made a mistake here https://github.com/eezhal92/resepku-node/commit/2ea5c982a315e4d01990cc203681a106a3778f2b#diff-0730bb7c2e8f9ea2438b52e419dd86c9R148.

`'Hello there!'` should be `"Hello there!"` because it's JSON code.

Simple fix ;)

**Comment by rgilbert1** [comment]
I'll fix it!

**Comment by mauzzr** [comment]
That was quick, seems Hacktoberfest is popular! :)

**Comment by eezhal92** [comment]
@pwelby Yeah, happy coding! :D
