### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by eezhal92** [eezhal92/resepku-node#16]
I performed a request to this endpoint `POST /recipes/:id/comments` without `text` body field and get this error.

This because in this block https://github.com/eezhal92/resepku-node/blob/master/src/app.js#L64, We don't do any check, whether `text` field present or not.

When the request body doesn't contains `text` field the response status should be `422` and the response body should be like this:
```json
{ "message": "`text` field should be present" }
```

**Comment by spencewine** [comment]
I'm on it.

**Comment by eezhal92** [comment]
Okay :D

**Comment by eezhal92** [comment]
@spencewine also, could you make test for this case? You can create new test function in `tests/recipes/comments/add.test.js`.

**Comment by jhondelbaguio** [comment]
@eezhal92 Got the problem here. I'll send a PR in a bit.

**Comment by eezhal92** [comment]
@jhondelbaguio i might merge @spencewine PR, since he's first :)

**Comment by jhondelbaguio** [comment]
@eezhal92 No problem :)

**Comment by eezhal92** [comment]
Closed by @ #17
