### ISSUE TITLE
Need to create tests for endpoints

### ISSUE THREAD

**Issue by eezhal92** [eezhal92/resepku-node#2]
This should be pretty straight forward 😄

**Comment by eezhal92** [comment]
If you already working on this, please comment "I'm working on this right now". The one who comment first, will get the PR merged.

**Comment by eezhal92** [comment]
I'm working on this lol

**Comment by jhondelbaguio** [comment]
I wanted to try this. but something urgent to do at work. Maybe i'll just support you with some endpoint test cases.

**Comment by eezhal92** [comment]
Closed with this PR #11
