### ISSUE TITLE
Need to create recipes module unit test

### ISSUE THREAD

**Issue by eezhal92** [eezhal92/resepku-node#3]
This should be pretty straight forward. Preferred test framework is jest :)

**Comment by eezhal92** [comment]
If you already working on this, please comment "I'm working on this right now". The one who comment first, will get the PR merged.

**Comment by karthick-manoharan** [comment]
@eezhal92 I'm working on this :)

**Comment by DSchau** [comment]
@karthick-manoharan I think I just finished it :/ Sorry for not seeing your comment!

**Comment by karthick-manoharan** [comment]
Np :)
