### ISSUE TITLE
Setup CI and automatic deployment

### ISSUE THREAD

**Issue by eezhal92** [eezhal92/resepku-node#9]
I'm going to handle this one.

**Comment by DSchau** [comment]
@eezhal92 I'd recommend using travis.ci :) It's so easy to set up

Not sure what the best "service" to deploy to is (i.e. if you actually want to deploy your mock server) but I'm sure there are some good options out there!

**Comment by eezhal92** [comment]
@DSchau I was using travis for my open source project, but I will go with circle ci :)
